/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package system;

import jaco.mp3.player.MP3Player;
import java.io.File;
import javax.swing.JFrame;

/**
 *
 * @author jeeva
 */
public class aboutUs extends javax.swing.JFrame {

    /**
     * Creates new form aboutUs
     */
    public aboutUs() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setExtendedState(JFrame.MAXIMIZED_HORIZ); 
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Credits = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(956, 491));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/About us/about.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 330, 130);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Who we are ?");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 130, 330, 120);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("    Credits");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 240, 330, 110);

        Credits.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Credits.setText("See Credits");
        Credits.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreditsActionPerformed(evt);
            }
        });
        jPanel1.add(Credits);
        Credits.setBounds(80, 370, 200, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 330, 490);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("This Airline Reservation System is made by Icse Student,Harshdeep.\n");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(0, 0, 620, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Currently studying in ........................ ");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 60, 343, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Under this Project You can- \n");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(10, 92, 580, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("1.Book Flight Tickets to:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 130, 540, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("1.Newyork    2.Agra   3.Punjab   4.India   5.Europe   6.Delhi\n\n\n\n     \n\n");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(20, 170, 600, 40);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("7.Chennai 8.Africa 9.Antartica 10. London  11. United Kingdom  ");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(10, 210, 600, 40);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText(" 12. HongKong  13. United States of America  14.Singapore,Etc.\n");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 250, 610, 40);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("2.You can cancel these tickets Incase you do not want to go ");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(20, 310, 570, 50);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText(" to the places whose tickets you have booked.");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(60, 350, 520, 40);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("3.The money paid for tickets which you have cancelled");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(30, 400, 580, 50);

        jSeparator1.setForeground(new java.awt.Color(51, 204, 255));
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(10, 90, 600, 10);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel2.add(jSeparator2);
        jSeparator2.setBounds(110, 160, 2, 0);

        jSeparator3.setForeground(new java.awt.Color(255, 153, 204));
        jPanel2.add(jSeparator3);
        jSeparator3.setBounds(10, 40, 590, 10);

        jSeparator4.setForeground(new java.awt.Color(0, 0, 255));
        jPanel2.add(jSeparator4);
        jSeparator4.setBounds(20, 310, 570, 10);

        jSeparator5.setForeground(new java.awt.Color(51, 51, 255));
        jPanel2.add(jSeparator5);
        jSeparator5.setBounds(20, 400, 590, 10);

        jSeparator6.setForeground(new java.awt.Color(51, 51, 255));
        jPanel2.add(jSeparator6);
        jSeparator6.setBounds(10, 120, 600, 10);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText(" is 100% Refundable.");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(30, 440, 570, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(330, 0, 630, 490);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CreditsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreditsActionPerformed
      this.dispose();
        credits show =new credits();
       show.setVisible(true);
    }//GEN-LAST:event_CreditsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
                new aboutUs().setVisible(true);
         
          
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Credits;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    // End of variables declaration//GEN-END:variables
}
