/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package system;

import jaco.mp3.player.MP3Player;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.JFrame;
import javax.swing.Timer;

/**
 *
 * @author jeeva
 */
public class Admin_Setup_page extends javax.swing.JFrame {

    
    public Admin_Setup_page() {
        initComponents();
         setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
         setExtendedState(JFrame.MAXIMIZED_HORIZ); 
        setResizable(false);
        deletef.setEnabled(false);
           addf.setEnabled(false);
           customer.setEnabled(false);
           details.setEnabled(false);
           m.setVisible(false);
    }
    public class po implements ActionListener{
       public void actionPerformed(ActionEvent evt){
         int n=m.getValue();
       if(n<100)
         {
             n++;
            
             m.setValue(n);
        
        
         }
      
         
         else{
             timer.stop();
              deletef.setEnabled(true);
           addf.setEnabled(true);
           customer.setEnabled(true);
           details.setEnabled(true);
           
             
         }
       }

    }
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        customer = new javax.swing.JButton();
        addf = new javax.swing.JButton();
        pass = new javax.swing.JPasswordField();
        deletef = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        details = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        sh = new javax.swing.JCheckBox();
        m = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(940, 615));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        customer.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        customer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/Admin/add.jpg"))); // NOI18N
        customer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerActionPerformed(evt);
            }
        });
        jPanel1.add(customer);
        customer.setBounds(690, 0, 220, 220);

        addf.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/Admin/Add flight.png"))); // NOI18N
        addf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addfActionPerformed(evt);
            }
        });
        jPanel1.add(addf);
        addf.setBounds(10, 350, 300, 160);

        pass.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.add(pass);
        pass.setBounds(330, 260, 300, 40);

        deletef.setBackground(new java.awt.Color(255, 255, 255));
        deletef.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        deletef.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/Admin/delete flight.png"))); // NOI18N
        deletef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletefActionPerformed(evt);
            }
        });
        jPanel1.add(deletef);
        deletef.setBounds(640, 330, 300, 170);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Highly Confidential");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(350, 110, 240, 40);

        details.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        details.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/Admin/details.jpg"))); // NOI18N
        details.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailsActionPerformed(evt);
            }
        });
        jPanel1.add(details);
        details.setBounds(10, 0, 220, 200);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setText("View Customer and ");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 200, 250, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel4.setText("Delete Flight");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(670, 520, 270, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel3.setText("Add Customer");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(710, 230, 210, 70);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton5.setText("-Go-");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(420, 340, 110, 40);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Please Enter Password again.");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(340, 180, 280, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel2.setText("Flight details");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 240, 270, 60);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("Add Flight");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 530, 250, 40);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(450, 30, 0, 2);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(630, 360, 310, 150);

        sh.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        sh.setText("Show Password");
        sh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shActionPerformed(evt);
            }
        });
        jPanel1.add(sh);
        sh.setBounds(330, 300, 300, 31);
        jPanel1.add(m);
        m.setBounds(320, 160, 270, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 940, 620);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
     String p= pass.getText();
        if(p.contains("I am Chitti 2.0"))
       {
            StartAdminSetup v=new StartAdminSetup();v.setVisible(true);
             timer=new Timer(290,new po());
             timer.start();
          
           
       }
        else
        {               new MP3Player(new File("C:\\Program Files\\Airline Reservation System\\src\\system\\Admin\\Security 1.mp3")).play();
            this.dispose();
            new securityBleach().setVisible(true);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void addfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addfActionPerformed
        Add_flight open=new Add_flight();
        open.setVisible(true);
    }//GEN-LAST:event_addfActionPerformed

    private void shActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shActionPerformed
if(sh.isSelected())
       {
           pass.setEchoChar((char)0);
       }
       else
       {
          pass.setEchoChar('*');
       }
                               
    }//GEN-LAST:event_shActionPerformed

    private void detailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailsActionPerformed
      
    }//GEN-LAST:event_detailsActionPerformed

    private void customerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerActionPerformed
       Add_costumer open=new  Add_costumer();
       open.setVisible(true);
    }//GEN-LAST:event_customerActionPerformed

    private void deletefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletefActionPerformed
        Delete_flight open=new Delete_flight();
        open.setVisible(true);
    }//GEN-LAST:event_deletefActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
                new Admin_Setup_page().setVisible(true);
        
    }
private Timer timer;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton addf;
    public static javax.swing.JButton customer;
    public static javax.swing.JButton deletef;
    public static javax.swing.JButton details;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JProgressBar m;
    private javax.swing.JPasswordField pass;
    private javax.swing.JCheckBox sh;
    // End of variables declaration//GEN-END:variables
}
