/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package system;

import jaco.mp3.player.MP3Player;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author jeeva
 */
public class Final_form2 extends javax.swing.JFrame {

    /**
     * Creates new form Final_form2
     */
    public Final_form2() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setExtendedState(JFrame.MAXIMIZED_HORIZ); 
        setResizable(false);
       a1.setVisible(false);bk.setVisible(false);
       b2.setVisible(false);b5.setVisible(false);b8.setVisible(false);
       b3.setVisible(false);b6.setVisible(false);b9.setVisible(false);
       b4.setVisible(false);b7.setVisible(false);b10.setVisible(false);
        j.setVisible(false);paisa.setVisible(false);omg.setVisible(false);
      o.setVisible(false);
      Continue.setEnabled(false);
    }

    private void s() {
        
        
    }
    public class p implements ActionListener{
       public void actionPerformed(ActionEvent evt){
         int n=j.getValue();
       if(n<100)
         {
             n++;
             o.setText(Integer.toString(n)+"%");
             j.setValue(n);
        
        
         }
         
         else
       {timer.stop();
           j.setVisible(false);
         o.setVisible(false);
             setVisible(false);
            Last_page_form open =new Last_page_form ();
         Last_page_form.f.setText(Final_form2.a1.getText());
        Last_page_form.ti.setText(Final_form2.b2.getText());
        Last_page_form.fn.setText(Final_form2.b3.getText());
        Last_page_form.ln.setText(Final_form2.b4.getText());
        Last_page_form.pn.setText(Final_form2.b5.getText());
        Last_page_form.pass.setText(Final_form2.b6.getText());
        Last_page_form.timers.setText(Final_form2.b7.getText());
        Last_page_form.dat.setText(Final_form2.b8.getText());
        Last_page_form.mo.setText(Final_form2.b9.getText());
         Last_page_form.yea.setText(Final_form2.b10.getText());
        Last_page_form.classof.setText(Final_form2.bk.getText());
        Last_page_form.rupees.setText(Final_form2.paisa.getText());
        Last_page_form.dol.setText(Final_form2.omg.getText());
     
        open.setVisible(true);
         new MP3Player(new File ("C:\\Program Files\\Airline Reservation System\\src\\system\\Home\\transactionlast.mp3")).play();
         }
       }
       
               
                       
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        a1 = new javax.swing.JLabel();
        b2 = new javax.swing.JLabel();
        b3 = new javax.swing.JLabel();
        b4 = new javax.swing.JLabel();
        b5 = new javax.swing.JLabel();
        b6 = new javax.swing.JLabel();
        b7 = new javax.swing.JLabel();
        b8 = new javax.swing.JLabel();
        b9 = new javax.swing.JLabel();
        b10 = new javax.swing.JLabel();
        bk = new javax.swing.JLabel();
        paisa = new javax.swing.JLabel();
        omg = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Continue = new javax.swing.JButton();
        Cancel = new javax.swing.JButton();
        o = new javax.swing.JLabel();
        j = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(723, 512));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 255));
        jLabel2.setText("To Complete your payment using Bank account ,fill out these details.\n");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 55, 650, 29);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(20, 90, 620, 10);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(110, 42, 320, 10);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator3);
        jSeparator3.setBounds(18, 90, 10, 240);
        getContentPane().add(jSeparator4);
        jSeparator4.setBounds(20, 330, 620, 20);

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator5);
        jSeparator5.setBounds(638, 90, 10, 240);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 255));
        jLabel3.setText("Enter Bank Account Number");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 120, 280, 30);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(380, 110, 230, 40);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 255));
        jLabel4.setText("Re-Enter Your Bank Account No.");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 180, 310, 30);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(380, 180, 230, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 255));
        jLabel5.setText("Enter Your IFSC Code");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 250, 260, 50);

        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField3KeyReleased(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(380, 260, 230, 40);

        a1.setText("jLabel6");
        getContentPane().add(a1);
        a1.setBounds(90, 350, 34, 14);

        b2.setText("jLabel6");
        getContentPane().add(b2);
        b2.setBounds(140, 350, 34, 14);

        b3.setText("jLabel7");
        getContentPane().add(b3);
        b3.setBounds(190, 350, 34, 14);

        b4.setText("jLabel8");
        getContentPane().add(b4);
        b4.setBounds(240, 350, 34, 14);

        b5.setText("jLabel9");
        getContentPane().add(b5);
        b5.setBounds(290, 350, 34, 14);

        b6.setText("jLabel10");
        getContentPane().add(b6);
        b6.setBounds(340, 350, 40, 14);

        b7.setText("jLabel11");
        getContentPane().add(b7);
        b7.setBounds(400, 350, 40, 14);

        b8.setText("jLabel12");
        getContentPane().add(b8);
        b8.setBounds(460, 350, 40, 14);

        b9.setText("jLabel13");
        getContentPane().add(b9);
        b9.setBounds(510, 350, 40, 14);

        b10.setText("jLabel14");
        getContentPane().add(b10);
        b10.setBounds(560, 350, 40, 14);

        bk.setText("jLabel15");
        getContentPane().add(bk);
        bk.setBounds(620, 350, 40, 14);

        paisa.setText("jLabel6");
        getContentPane().add(paisa);
        paisa.setBounds(40, 350, 34, 14);

        omg.setText("jLabel6");
        getContentPane().add(omg);
        omg.setBounds(670, 350, 34, 14);

        jPanel2.setBackground(new java.awt.Color(204, 255, 204));
        jPanel2.setLayout(null);

        jLabel1.setBackground(new java.awt.Color(102, 255, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 102));
        jLabel1.setText("Complete Your Payment");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(116, 0, 454, 44);

        Continue.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Continue.setForeground(new java.awt.Color(255, 0, 255));
        Continue.setText("Continue");
        Continue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinueActionPerformed(evt);
            }
        });
        jPanel2.add(Continue);
        Continue.setBounds(190, 390, 140, 40);

        Cancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Cancel.setForeground(new java.awt.Color(255, 0, 255));
        Cancel.setText("Cancel");
        Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelActionPerformed(evt);
            }
        });
        jPanel2.add(Cancel);
        Cancel.setBounds(440, 390, 160, 40);

        o.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        o.setText("100%");
        jPanel2.add(o);
        o.setBounds(340, 440, 61, 27);

        j.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        j.setForeground(new java.awt.Color(204, 255, 204));
        j.setString("Sending Transaction Request..Please wait till it completes..");
        j.setStringPainted(true);
        jPanel2.add(j);
        j.setBounds(0, 470, 720, 27);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 720, 510);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinueActionPerformed
      j.setVisible(true);
      o.setVisible(true);
          timer=new Timer(50,new p());
        timer.start(); 
     
    }//GEN-LAST:event_ContinueActionPerformed

    private void CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelActionPerformed
       new MP3Player(new File("C:\\Program Files\\Airline Reservation System\\src\\system\\Home\\Cancel.mp3")).play(); 
        int x= JOptionPane.showConfirmDialog(null, "Do you want to exit and stop booking the tickets",
                "Cancel",JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE);
        if(x==JOptionPane.YES_OPTION)
        {
            this.dispose();
        }
        else
        {
            
        }
    }//GEN-LAST:event_CancelActionPerformed

    private void jTextField3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyReleased
         Continue.setEnabled(true);
    }//GEN-LAST:event_jTextField3KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
                new Final_form2().setVisible(true);
               
          
    }
private Timer timer;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancel;
    private javax.swing.JButton Continue;
    public static javax.swing.JLabel a1;
    public static javax.swing.JLabel b10;
    public static javax.swing.JLabel b2;
    public static javax.swing.JLabel b3;
    public static javax.swing.JLabel b4;
    public static javax.swing.JLabel b5;
    public static javax.swing.JLabel b6;
    public static javax.swing.JLabel b7;
    public static javax.swing.JLabel b8;
    public static javax.swing.JLabel b9;
    public static javax.swing.JLabel bk;
    private javax.swing.JProgressBar j;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel o;
    public static javax.swing.JLabel omg;
    public static javax.swing.JLabel paisa;
    // End of variables declaration//GEN-END:variables
}
