/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package system;

import jaco.mp3.player.MP3Player;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author jeeva
 */
public class Final_Form extends javax.swing.JFrame {

    /**
     * Creates new form Final_Form
     */
    public Final_Form() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setExtendedState(JFrame.MAXIMIZED_HORIZ); 
        setResizable(false); j.setVisible(false);priced.setVisible(false);
             o.setVisible(false);   Continue.setEnabled(false);
        da.setVisible(false);rk.setVisible(false);pricer.setVisible(false);
         db.setVisible(false); de.setVisible(false); dh.setVisible(false);
          dc.setVisible(false); df.setVisible(false); di.setVisible(false);
           dd.setVisible(false); dg.setVisible(false); dj.setVisible(false);
    }
 public class p implements ActionListener{
       public void actionPerformed(ActionEvent evt){
         int n=j.getValue();
       if(n<100)
         {
             n++;
             o.setText(Integer.toString(n)+"%");
             j.setValue(n);
        
        
         }
      
         
         else{
             timer.stop();
            
             j.setVisible(false);
             o.setVisible(false);
             setVisible(false);
             setVisible(false);
              Last_page_form open =new Last_page_form ();
         Last_page_form.f.setText(Final_Form.da.getText());
        Last_page_form.ti.setText(Final_Form.db.getText());
        Last_page_form.fn.setText(Final_Form.dc.getText());
        Last_page_form.ln.setText(Final_Form.dd.getText());
        Last_page_form.pn.setText(Final_Form.de.getText());
        Last_page_form.pass.setText(Final_Form.df.getText());
        Last_page_form.timers.setText(Final_Form.dg.getText());
        Last_page_form.dat.setText(Final_Form.dh.getText());
        Last_page_form.mo.setText(Final_Form.di.getText());
         Last_page_form.yea.setText(Final_Form.dj.getText());
         Last_page_form.classof.setText(Final_Form.rk.getText());
         Last_page_form.dol.setText(Final_Form.priced.getText());
         Last_page_form.rupees.setText(Final_Form.pricer.getText());
        open.setVisible(true);
         new MP3Player(new File ("C:\\Program Files\\Airline Reservation System\\src\\system\\Home\\transactionlast.mp3")).play();
         }
       }
       
               
                       
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        card = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        twothousand = new javax.swing.JTextField();
        code = new javax.swing.JTextField();
        ye = new javax.swing.JComboBox<>();
        cardc = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        dat = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        da = new javax.swing.JLabel();
        db = new javax.swing.JLabel();
        dc = new javax.swing.JLabel();
        dd = new javax.swing.JLabel();
        de = new javax.swing.JLabel();
        df = new javax.swing.JLabel();
        dg = new javax.swing.JLabel();
        dh = new javax.swing.JLabel();
        di = new javax.swing.JLabel();
        dj = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        Continue = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        three = new javax.swing.JTextField();
        july = new javax.swing.JTextField();
        mo = new javax.swing.JComboBox<>();
        rk = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        j = new javax.swing.JProgressBar();
        o = new javax.swing.JLabel();
        pricer = new javax.swing.JLabel();
        priced = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(862, 554));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(763, 0, 0, 0);

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));
        jPanel1.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Credit Card Number:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(100, 280, 186, 22);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Credit Card Name:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(100, 170, 166, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Name on Credit Card:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(100, 230, 194, 22);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Expiration Date:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(100, 340, 147, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Security Code:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(110, 400, 131, 22);

        card.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        card.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardActionPerformed(evt);
            }
        });
        jPanel1.add(card);
        card.setBounds(450, 160, 200, 30);

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(jTextField2);
        jTextField2.setBounds(490, 220, 290, 30);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField3);
        jTextField3.setBounds(450, 280, 330, 30);
        jPanel1.add(twothousand);
        twothousand.setBounds(659, 330, 50, 40);

        code.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                codeKeyTyped(evt);
            }
        });
        jPanel1.add(code);
        code.setBounds(450, 390, 230, 30);

        ye.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", "2041", "2042", "2043", "2044", "2045", "2046", "2047", "2048", "2049", " ", " " }));
        ye.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yeActionPerformed(evt);
            }
        });
        jPanel1.add(ye);
        ye.setBounds(710, 330, 70, 40);

        cardc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1.Mastercard ", "2.Visa ", "3.SBI", "4.Paypal ", "5.Discover", " 6.ICCI", " 7.Punjab card", " 8.Axis" }));
        cardc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cardcActionPerformed(evt);
            }
        });
        jPanel1.add(cardc);
        cardc.setBounds(650, 160, 130, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(51, 51, 255));
        jButton3.setText("help");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(680, 390, 100, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Mr.");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(450, 214, 40, 40);

        dat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", " " }));
        dat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datActionPerformed(evt);
            }
        });
        jPanel1.add(dat);
        dat.setBounds(480, 330, 40, 40);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Complete Your Payment");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(180, 0, 457, 64);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("To Pay by Debit/ Credit Card ,Please fill out these details:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(41, 80, 730, 29);

        da.setText("jLabel5");
        jPanel1.add(da);
        da.setBounds(330, 140, 34, 14);

        db.setText("jLabel11");
        jPanel1.add(db);
        db.setBounds(340, 210, 40, 14);

        dc.setText("jLabel12");
        jPanel1.add(dc);
        dc.setBounds(340, 250, 40, 14);

        dd.setText("jLabel13");
        jPanel1.add(dd);
        dd.setBounds(340, 290, 40, 14);

        de.setText("jLabel14");
        jPanel1.add(de);
        de.setBounds(340, 330, 40, 14);

        df.setText("jLabel15");
        jPanel1.add(df);
        df.setBounds(340, 370, 40, 14);

        dg.setText("jLabel16");
        jPanel1.add(dg);
        dg.setBounds(340, 410, 40, 14);

        dh.setText("jLabel17");
        jPanel1.add(dh);
        dh.setBounds(280, 420, 40, 14);

        di.setText("jLabel18");
        jPanel1.add(di);
        di.setBounds(280, 200, 40, 14);

        dj.setText("jLabel19");
        jPanel1.add(dj);
        dj.setBounds(330, 180, 40, 14);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(50, 120, 780, 2);

        jPanel2.setBackground(new java.awt.Color(153, 255, 153));
        jPanel2.setLayout(null);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 255));
        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(260, 0, 160, 50);

        Continue.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Continue.setForeground(new java.awt.Color(51, 51, 255));
        Continue.setText("Continue");
        Continue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinueActionPerformed(evt);
            }
        });
        jPanel2.add(Continue);
        Continue.setBounds(0, 0, 170, 50);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(360, 450, 420, 50);

        jPanel3.setLayout(null);
        jPanel3.add(three);
        three.setBounds(0, 0, 30, 40);
        jPanel3.add(july);
        july.setBounds(70, 0, 60, 40);

        mo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December", " " }));
        mo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moActionPerformed(evt);
            }
        });
        jPanel3.add(mo);
        mo.setBounds(130, 0, 80, 40);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(450, 330, 330, 40);

        rk.setText("jLabel5");
        jPanel1.add(rk);
        rk.setBounds(280, 150, 34, 14);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(50, 430, 780, 2);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(48, 122, 10, 310);
        jPanel1.add(jSeparator4);
        jSeparator4.setBounds(800, 140, 0, 2);

        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator5);
        jSeparator5.setBounds(828, 120, 10, 310);

        j.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        j.setForeground(new java.awt.Color(153, 255, 153));
        j.setString("Sending Transaction Request..Please wait till it completes..");
        j.setStringPainted(true);
        jPanel1.add(j);
        j.setBounds(0, 520, 790, 20);

        o.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        o.setForeground(new java.awt.Color(0, 51, 255));
        o.setText("100%");
        jPanel1.add(o);
        o.setBounds(790, 520, 70, 22);

        pricer.setText("jLabel5");
        jPanel1.add(pricer);
        pricer.setBounds(280, 260, 34, 14);

        priced.setText("jLabel11");
        jPanel1.add(priced);
        priced.setBounds(280, 310, 40, 14);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 860, 550);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cardActionPerformed

    private void ContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinueActionPerformed
       j.setVisible(true);
      o.setVisible(true);
          timer=new Timer(50,new p());
        timer.start(); 
       
    }//GEN-LAST:event_ContinueActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void datActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datActionPerformed
String selectedValue=dat.getSelectedItem().toString();
        three.setText(selectedValue);        
    }//GEN-LAST:event_datActionPerformed

    private void moActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moActionPerformed
      String selectedValue=mo.getSelectedItem().toString();
        july.setText(selectedValue);        
    }//GEN-LAST:event_moActionPerformed

    private void yeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yeActionPerformed
String selectedValue=ye.getSelectedItem().toString();
        twothousand.setText(selectedValue);             
    }//GEN-LAST:event_yeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       new MP3Player(new File("C:\\Program Files\\Airline Reservation System\\src\\system\\Home\\Cancel.mp3")).play(); 
        int x= JOptionPane.showConfirmDialog(null, "Do you want to exit and stop booking the tickets",
                "Cancel",JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE);
        if(x==JOptionPane.YES_OPTION)
        {
            this.dispose();
        }
        else
        {
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void codeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_codeKeyTyped
       Continue.setEnabled(true);
    }//GEN-LAST:event_codeKeyTyped

    private void cardcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cardcActionPerformed
        String selectedValue=cardc.getSelectedItem().toString();
        card.setText(selectedValue);   
    }//GEN-LAST:event_cardcActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
             new MP3Player(new File ("C:\\Program Files\\Airline Reservation System\\src\\system\\Home\\pleas.mp3")).play();
        String t="Please enter Your Four digit atm pin...Do not worry it is 100%secure. Or";
      String r="If you wish to close this,Click cancel to stop this Payment process"; 
      String et=t+r;
        JOptionPane.showMessageDialog(null, et);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
                new Final_Form().setVisible(true);
               
    }
private Timer timer;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Continue;
    private javax.swing.JTextField card;
    private javax.swing.JComboBox<String> cardc;
    private javax.swing.JTextField code;
    public static javax.swing.JLabel da;
    private javax.swing.JComboBox<String> dat;
    public static javax.swing.JLabel db;
    public static javax.swing.JLabel dc;
    public static javax.swing.JLabel dd;
    public static javax.swing.JLabel de;
    public static javax.swing.JLabel df;
    public static javax.swing.JLabel dg;
    public static javax.swing.JLabel dh;
    public static javax.swing.JLabel di;
    public static javax.swing.JLabel dj;
    private javax.swing.JProgressBar j;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField july;
    private javax.swing.JComboBox<String> mo;
    private javax.swing.JLabel o;
    public static javax.swing.JLabel priced;
    public static javax.swing.JLabel pricer;
    public static javax.swing.JLabel rk;
    private javax.swing.JTextField three;
    private javax.swing.JTextField twothousand;
    private javax.swing.JComboBox<String> ye;
    // End of variables declaration//GEN-END:variables
}
