/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package system;

import jaco.mp3.player.MP3Player;
import java.io.File;
import javax.swing.JFrame;

/**
 *
 * @author jeeva
 */
public class Form_fill2 extends javax.swing.JFrame {

    /**
     * Creates new form Form_fill2
     */
    public Form_fill2() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setExtendedState(JFrame.MAXIMIZED_HORIZ); 
        setResizable(false);
        Next.setEnabled(false);
         fromlondon.setVisible(false);
                tojapan.setVisible(false);
               p1.setVisible(false);
               p2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        lname = new javax.swing.JTextField();
        passenger = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        time = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Next = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        date = new javax.swing.JTextField();
        datec = new javax.swing.JComboBox<>();
        month = new javax.swing.JTextField();
        monthc = new javax.swing.JComboBox<>();
        year = new javax.swing.JTextField();
        yearc = new javax.swing.JComboBox<>();
        fromlondon = new javax.swing.JLabel();
        tojapan = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Class = new javax.swing.JTextField();
        classc = new javax.swing.JComboBox<>();
        p1 = new javax.swing.JLabel();
        p2 = new javax.swing.JLabel();
        hp = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();

        jLabel8.setText("\n");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1010, 682));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("First Name");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(70, 100, 137, 38);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Last Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(70, 170, 217, 35);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("No. Of Passengers");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(60, 250, 217, 32);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Phone Number");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(67, 421, 217, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Time");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(67, 500, 189, 27);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Date of Departing");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(50, 570, 230, 30);

        fname.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(fname);
        fname.setBounds(420, 90, 320, 40);

        lname.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(lname);
        lname.setBounds(420, 170, 320, 35);

        passenger.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(passenger);
        passenger.setBounds(420, 250, 250, 40);

        phone.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jPanel1.add(phone);
        phone.setBounds(431, 424, 320, 36);

        time.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        time.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                timeKeyReleased(evt);
            }
        });
        jPanel1.add(time);
        time.setBounds(431, 503, 320, 33);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Fill your Details");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(180, 0, 380, 65);

        Next.setBackground(new java.awt.Color(255, 255, 255));
        Next.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Next.setForeground(new java.awt.Color(0, 51, 255));
        Next.setText("Next");
        Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextActionPerformed(evt);
            }
        });
        jPanel1.add(Next);
        Next.setBounds(810, 610, 130, 40);

        jPanel2.setLayout(null);
        jPanel2.add(date);
        date.setBounds(0, 0, 30, 40);

        datec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", " " }));
        datec.setMinimumSize(new java.awt.Dimension(6, 20));
        datec.setPreferredSize(new java.awt.Dimension(6, 20));
        datec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datecActionPerformed(evt);
            }
        });
        jPanel2.add(datec);
        datec.setBounds(30, 0, 40, 40);
        jPanel2.add(month);
        month.setBounds(69, 0, 60, 40);

        monthc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December", " " }));
        monthc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthcActionPerformed(evt);
            }
        });
        jPanel2.add(monthc);
        monthc.setBounds(127, 0, 80, 40);
        jPanel2.add(year);
        year.setBounds(200, 0, 50, 40);

        yearc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029", "2030", "2031", "2032", "2033", "2034", "2035", "2036", "2037", "2038", "2039", "2040", "2041", "2042", "2043", "2044", "2045", "2046", "2047", "2048", " " }));
        yearc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearcActionPerformed(evt);
            }
        });
        jPanel2.add(yearc);
        yearc.setBounds(250, 0, 70, 40);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(430, 570, 320, 40);

        fromlondon.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        fromlondon.setText("jLabel9");
        jPanel1.add(fromlondon);
        fromlondon.setBounds(520, 20, 180, 30);

        tojapan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tojapan.setText("jLabel10");
        jPanel1.add(tojapan);
        tojapan.setBounds(710, 20, 210, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Select Your Class ");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(60, 310, 270, 60);
        jPanel1.add(Class);
        Class.setBounds(420, 320, 170, 40);

        classc.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        classc.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Economy class", "Bussiness class" }));
        classc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classcActionPerformed(evt);
            }
        });
        jPanel1.add(classc);
        classc.setBounds(586, 320, 160, 40);

        p1.setText("jLabel5");
        jPanel1.add(p1);
        p1.setBounds(780, 320, 110, 30);

        p2.setText("jLabel10");
        jPanel1.add(p2);
        p2.setBounds(780, 360, 40, 14);

        hp.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        hp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1" }));
        hp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hpActionPerformed(evt);
            }
        });
        jPanel1.add(hp);
        hp.setBounds(670, 250, 70, 40);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/Home/form2.jpg"))); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(0, 0, 1010, 660);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1010, 660);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextActionPerformed
this.dispose();        
        Payment_method open=new Payment_method();
        Payment_method.a.setText(Form_fill2.fromlondon.getText());
        Payment_method.b.setText(Form_fill2.tojapan.getText());
        Payment_method.c.setText(Form_fill2.fname.getText());
        Payment_method.d.setText(Form_fill2.lname.getText());
        Payment_method.e.setText(Form_fill2.passenger.getText());
        Payment_method.f.setText(Form_fill2.phone.getText());
        Payment_method.g.setText(Form_fill2.time.getText());
        Payment_method.h.setText(Form_fill2.date.getText());
        Payment_method.i.setText(Form_fill2.month.getText());
        Payment_method.j.setText(Form_fill2.year.getText());
       
        Payment_method.rupee.setText(Form_fill2.p1.getText());
        Payment_method.dollar.setText(Form_fill2.p2.getText());
         Payment_method.k.setText(Form_fill2.Class.getText());
        open.setVisible(true);
         new MP3Player(new File ("C:\\Program Files\\Airline Reservation System\\src\\system\\Home\\payment.mp3")).play();
    }//GEN-LAST:event_NextActionPerformed

    private void datecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datecActionPerformed
        String selectedValue=datec.getSelectedItem().toString();
        date.setText(selectedValue);
        
    }//GEN-LAST:event_datecActionPerformed

    private void monthcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthcActionPerformed
      
        String selectedValue=monthc.getSelectedItem().toString();
        month.setText(selectedValue);
        
    }//GEN-LAST:event_monthcActionPerformed

    private void yearcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearcActionPerformed
       String selectedValue=yearc.getSelectedItem().toString();
        year.setText(selectedValue);
        
    }//GEN-LAST:event_yearcActionPerformed

    private void timeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_timeKeyReleased
       Next.setEnabled(true);
    }//GEN-LAST:event_timeKeyReleased

    private void classcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classcActionPerformed
      String selectedValue=classc.getSelectedItem().toString();
        Class.setText(selectedValue);          
       if(selectedValue=="Bussiness class"){
            p1.setText("18000");
            p2.setText("277$");
        }
       else if(selectedValue=="Economy class"){
            p1.setText("14000");
            p2.setText("200$");
        }
    }//GEN-LAST:event_classcActionPerformed

    private void hpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hpActionPerformed
          String selectedValue=hp.getSelectedItem().toString();
        passenger.setText(selectedValue);    
        
    }//GEN-LAST:event_hpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
                new Form_fill2().setVisible(true);
               
          new MP3Player(new File("C:\\Program Files\\Airline Reservation System\\src\\system\\Home\\form2.mp3")).play();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField Class;
    private javax.swing.JButton Next;
    private javax.swing.JComboBox<String> classc;
    public static javax.swing.JTextField date;
    private javax.swing.JComboBox<String> datec;
    public static javax.swing.JTextField fname;
    public static javax.swing.JLabel fromlondon;
    private javax.swing.JComboBox<String> hp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JTextField lname;
    public static javax.swing.JTextField month;
    private javax.swing.JComboBox<String> monthc;
    public static javax.swing.JLabel p1;
    public static javax.swing.JLabel p2;
    public static javax.swing.JTextField passenger;
    public static javax.swing.JTextField phone;
    public static javax.swing.JTextField time;
    public static javax.swing.JLabel tojapan;
    public static javax.swing.JTextField year;
    private javax.swing.JComboBox<String> yearc;
    // End of variables declaration//GEN-END:variables
}
