/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package system;

import jaco.mp3.player.MP3Player;
import java.io.File;
import javax.swing.JFrame;

/**
 *
 * @author jeeva
 */
public class Form_fill1 extends javax.swing.JFrame {

    /**
     * Creates new form Form_fill1
     */
    public Form_fill1() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setExtendedState(JFrame.MAXIMIZED_HORIZ); 
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        to2 = new javax.swing.JTextField();
        from1 = new javax.swing.JTextField();
        from = new javax.swing.JComboBox<>();
        to = new javax.swing.JComboBox<>();
        Next = new javax.swing.JButton();
        tc = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1053, 682));
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 255));
        jLabel4.setText("To");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(800, 290, 80, 44);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Choose  Your  Destination");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(270, 60, 490, 44);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("From");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(140, 290, 120, 50);

        to2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        to2.setText("SingaPore");
        to2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                to2ActionPerformed(evt);
            }
        });
        getContentPane().add(to2);
        to2.setBounds(670, 430, 170, 40);

        from1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        from1.setText("NewYork");
        getContentPane().add(from1);
        from1.setBounds(130, 430, 170, 40);

        from.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Europe", "NewYork", "Africa", "Antartica ", "India ", "London", "United States of America", "United Kingdom", "HongKong", "Singapore", "Agra", "Delhi", "Chennai", "Punjab", "Delhi", " ", " " }));
        from.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fromActionPerformed(evt);
            }
        });
        getContentPane().add(from);
        from.setBounds(300, 430, 100, 40);

        to.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "India ", "Singapore", "HongKong", "United Kingdom", "Antartica ", "Egypt", "London", "United States of America", "NewYork", "Europe", "Africa", "Punjab", "Agra", "Delhi", "Chennai", " ", " ", " ", " " }));
        to.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toActionPerformed(evt);
            }
        });
        getContentPane().add(to);
        to.setBounds(840, 430, 100, 40);

        Next.setBackground(new java.awt.Color(51, 153, 255));
        Next.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Next.setText("Next");
        Next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NextActionPerformed(evt);
            }
        });
        getContentPane().add(Next);
        Next.setBounds(470, 570, 120, 40);

        tc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/Home/form1.jpg"))); // NOI18N
        tc.setText("jLabel5");
        getContentPane().add(tc);
        tc.setBounds(0, 0, 1050, 680);

        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(700, 120, 34, 14);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void NextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NextActionPerformed
this.dispose();       
         Form_fill2 open =new Form_fill2();
        
       
        Form_fill2.fromlondon.setText(from1.getText());
         Form_fill2.tojapan.setText(to2.getText());
     
         
       open.setVisible(true);
       new MP3Player(new File ("C:\\Program Files\\Airline Reservation System\\src\\system\\Home\\fill2.mp3")).play();
         
    }//GEN-LAST:event_NextActionPerformed
public static void select(){
   String r=from1.getText();  double perticket;  
      double d;
   String f=to2.getText();
   
}
    private void fromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fromActionPerformed
        String selectedValue=from.getSelectedItem().toString();
        from1.setText(selectedValue);
        
    }//GEN-LAST:event_fromActionPerformed

    private void toActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toActionPerformed
            String selectedValue=to.getSelectedItem().toString();
        to2.setText(selectedValue);
        
    }//GEN-LAST:event_toActionPerformed

    private void to2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_to2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_to2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
                new Form_fill1().setVisible(true);
          
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Next;
    private javax.swing.JComboBox<String> from;
    public static javax.swing.JTextField from1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel tc;
    private javax.swing.JComboBox<String> to;
    public static javax.swing.JTextField to2;
    // End of variables declaration//GEN-END:variables
}
