/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package system;

import jaco.mp3.player.MP3Player;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.JFrame;
import javax.swing.Timer;

/**
 *
 * @author jeeva
 */
public class Last_page_form extends javax.swing.JFrame {

    /**
     * Creates new form Last_page_form
     */
    public Last_page_form() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setExtendedState(JFrame.MAXIMIZED_HORIZ); 
        setResizable(false);
        j.setVisible(false);
    }
 public class p implements ActionListener{
       public void actionPerformed(ActionEvent evt){
         int n=j.getValue();
       if(n<100)
         {
             n++;
             
             j.setValue(n);
        
        
         }
      
         
         else{
             timer.stop();
            j.setVisible(false);
            setVisible(false);
            
         }
       }
       
               
                       
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        o = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        f = new javax.swing.JLabel();
        fn = new javax.swing.JLabel();
        pn = new javax.swing.JLabel();
        timers = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ti = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        ln = new javax.swing.JLabel();
        pass = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        dat = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        dol = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        rupees = new javax.swing.JLabel();
        rup = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        mo = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        yea = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        classof = new javax.swing.JLabel();
        j = new javax.swing.JProgressBar();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(920, 613));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Transaction Successful !!");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(180, 0, 600, 60);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Thank you Sir for booking tickets from us.");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(130, 50, 580, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel3.setText("Here are the details of your booking.\n");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(160, 100, 330, 50);

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel26.setText("For any Problem,Please click the help button provided on home page.\n\n");
        jPanel1.add(jLabel26);
        jLabel26.setBounds(10, 510, 870, 40);

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel27.setText("Have a Good Day Sir.Thank You for Booking Flight Tickets from us.");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(10, 470, 860, 40);

        o.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        o.setText("\nWe are directing you back to home page after 15 seconds.");
        jPanel1.add(o);
        o.setBounds(60, 550, 760, 29);
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(10, 150, 0, 2);
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(0, 140, 920, 10);

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));
        jPanel3.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("From");
        jPanel3.add(jLabel5);
        jLabel5.setBounds(0, 21, 90, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel7.setText("First name");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(0, 77, 150, 29);

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setText("Phone Number");
        jPanel3.add(jLabel15);
        jLabel15.setBounds(400, 130, 230, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Time");
        jPanel3.add(jLabel4);
        jLabel4.setBounds(0, 183, 140, 29);

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel20.setText("You have Payed ");
        jPanel3.add(jLabel20);
        jLabel20.setBounds(0, 248, 240, 29);

        f.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        f.setText("-");
        jPanel3.add(f);
        f.setBounds(191, 11, 194, 40);

        fn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        fn.setText("-");
        jPanel3.add(fn);
        fn.setBounds(191, 79, 190, 30);

        pn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pn.setText("-");
        jPanel3.add(pn);
        pn.setBounds(250, 140, 120, 40);

        timers.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        timers.setText("-");
        jPanel3.add(timers);
        timers.setBounds(198, 185, 160, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setText("To");
        jPanel3.add(jLabel6);
        jLabel6.setBounds(400, 20, 140, 30);

        ti.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ti.setText("-");
        jPanel3.add(ti);
        ti.setBounds(667, 16, 210, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel11.setText("Last name");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(393, 79, 160, 30);

        ln.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ln.setText("-");
        jPanel3.add(ln);
        ln.setBounds(667, 79, 210, 30);

        pass.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pass.setText("-");
        jPanel3.add(pass);
        pass.setBounds(670, 140, 210, 30);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setText("No.Of Passengers");
        jLabel13.setToolTipText("");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(0, 130, 240, 40);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel16.setText("Date of Departing");
        jPanel3.add(jLabel16);
        jLabel16.setBounds(397, 183, 250, 40);

        dat.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dat.setText("1");
        jPanel3.add(dat);
        dat.setBounds(653, 181, 40, 50);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel22.setText("Usd");
        jPanel3.add(jLabel22);
        jLabel22.setBounds(597, 254, 33, 22);

        dol.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dol.setText("jLabel25");
        jPanel3.add(dol);
        dol.setBounds(477, 254, 110, 22);

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel23.setText("Or");
        jPanel3.add(jLabel23);
        jLabel23.setBounds(380, 260, 50, 22);

        rupees.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rupees.setText("jLabel21");
        jPanel3.add(rupees);
        rupees.setBounds(210, 250, 100, 30);

        rup.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rup.setText("Rupees");
        jPanel3.add(rup);
        rup.setBounds(310, 250, 67, 30);

        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel3.add(jSeparator4);
        jSeparator4.setBounds(389, 0, 30, 300);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("/");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(698, 184, 30, 50);

        mo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        mo.setText("January");
        jPanel3.add(mo);
        mo.setBounds(727, 183, 80, 50);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("/");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(806, 184, 20, 50);

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));
        jPanel2.setLayout(null);

        yea.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        yea.setText("2000");
        jPanel2.add(yea);
        yea.setBounds(170, 10, 50, 40);

        jPanel3.add(jPanel2);
        jPanel2.setBounds(650, 180, 230, 50);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 140, 920, 300);
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(0, 440, 920, 10);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Booking Class-");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(560, 110, 140, 30);

        classof.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        classof.setText("jLabel12");
        jPanel1.add(classof);
        classof.setBounds(710, 110, 180, 30);

        j.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        j.setString("Redirecting...Please wait till it completes..");
        j.setStringPainted(true);
        jPanel1.add(j);
        j.setBounds(0, 584, 920, 26);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel12.setText("If your details displayed here are correct click Ok button.");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(10, 440, 690, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(750, 440, 80, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 920, 610);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      j.setVisible(true);
        timer=new Timer(50,new p());
        timer.start(); 
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
                new Last_page_form().setVisible(true);
                  new MP3Player(new File("C:\\Program Files\\Airline Reservation System\\src\\system\\Home\\transaction last.mp3")).play();
          
         
    }
private Timer timer;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel classof;
    public static javax.swing.JLabel dat;
    public static javax.swing.JLabel dol;
    public static javax.swing.JLabel f;
    public static javax.swing.JLabel fn;
    private javax.swing.JProgressBar j;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    public static javax.swing.JLabel ln;
    public static javax.swing.JLabel mo;
    private javax.swing.JLabel o;
    public static javax.swing.JLabel pass;
    public static javax.swing.JLabel pn;
    public static javax.swing.JLabel rup;
    public static javax.swing.JLabel rupees;
    public static javax.swing.JLabel ti;
    public static javax.swing.JLabel timers;
    public static javax.swing.JLabel yea;
    // End of variables declaration//GEN-END:variables
}
