/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package system;

import jaco.mp3.player.MP3Player;
import java.io.File;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author jeeva
 */
public class Loginpage extends javax.swing.JFrame {

    
    public Loginpage() {
        initComponents();
        
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setExtendedState(JFrame.MAXIMIZED_HORIZ); 
        setResizable(false);
        use.setVisible(false);
        password.setVisible(false);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        User = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Pass = new javax.swing.JPasswordField();
        ji = new javax.swing.JCheckBox();
        U = new javax.swing.JLabel();
        P = new javax.swing.JLabel();
        use = new javax.swing.JTextField();
        password = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/Users/Button images/user.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(299, 0, 230, 250);

        User.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserActionPerformed(evt);
            }
        });
        User.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                UserKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                UserKeyReleased(evt);
            }
        });
        jPanel1.add(User);
        User.setBounds(410, 260, 400, 60);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 102, 255));
        jLabel1.setText("UserName");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(80, 260, 265, 60);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 102, 255));
        jLabel2.setText("Password");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 380, 265, 60);

        login.setBackground(new java.awt.Color(255, 255, 255));
        login.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        login.setForeground(new java.awt.Color(51, 102, 255));
        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel1.add(login);
        login.setBounds(180, 530, 175, 37);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 102, 255));
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(500, 530, 177, 37);

        Pass.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        Pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                PassKeyReleased(evt);
            }
        });
        jPanel1.add(Pass);
        Pass.setBounds(410, 390, 400, 50);

        ji.setBackground(new java.awt.Color(255, 255, 255));
        ji.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ji.setForeground(new java.awt.Color(51, 102, 255));
        ji.setText("Show Password");
        ji.setMaximumSize(new java.awt.Dimension(6, 20));
        ji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jiActionPerformed(evt);
            }
        });
        jPanel1.add(ji);
        ji.setBounds(410, 460, 410, 30);

        U.setBackground(new java.awt.Color(255, 255, 255));
        U.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        U.setForeground(new java.awt.Color(51, 153, 255));
        U.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        U.setMinimumSize(new java.awt.Dimension(6, 35));
        jPanel1.add(U);
        U.setBounds(411, 293, 400, 30);

        P.setBackground(new java.awt.Color(255, 255, 255));
        P.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        P.setForeground(new java.awt.Color(0, 153, 255));
        P.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        P.setMinimumSize(new java.awt.Dimension(6, 35));
        jPanel1.add(P);
        P.setBounds(400, 400, 410, 30);

        use.setText("jTextField1");
        jPanel1.add(use);
        use.setBounds(670, 40, 59, 20);

        password.setText("jTextField2");
        jPanel1.add(password);
        password.setBounds(670, 70, 59, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 871, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 871, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 611, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserActionPerformed

    }//GEN-LAST:event_UserActionPerformed

    private void UserKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UserKeyPressed

    }//GEN-LAST:event_UserKeyPressed

    private void UserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_UserKeyReleased
        U.setText("");
    }//GEN-LAST:event_UserKeyReleased

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed

        String pass= Pass.getText();
        String user= User.getText();
        if(User.getText().trim().isEmpty() && Pass.getText().trim().isEmpty()){
            U.setText("Username Field should not be left empty");
            P.setText("Password Field should not be left empty");
        }
        else if(User.getText().trim().isEmpty())
        {
            U.setText("Username Field should not be left empty");
        }
        else if(Pass.getText().trim().isEmpty())
        {
            P.setText("Password Field should not be left empty");
        }
        {

            User();

        }
    }//GEN-LAST:event_loginActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Pass.setText(null);
        User.setText(null);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void PassKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PassKeyReleased
        P.setText("");
    }//GEN-LAST:event_PassKeyReleased
 //----Sound Methods from Sound1 to Sound6
 //These are the methods to play sound effects.
       public static void Sound1()
{ new MP3Player(new File ("C:\\Program Files\\Airline Reservation System\\src\\system\\Users\\Audios\\user1.mp3")).play();}
    
      public static void Sound2()
{ new MP3Player(new File ("C:\\Program Files\\Airline Reservation System\\src\\system\\Users\\Audios\\user2.mp3")).play();}
    
     public static void Sound3()
{ new MP3Player(new File ("C:\\Program Files\\Airline Reservation System\\src\\system\\Users\\Audios\\user3.mp3")).play();}
    
     public static void Sound4()
{ new MP3Player(new File ("C:\\Program Files\\Airline Reservation System\\src\\system\\Users\\Audios\\user4.mp3")).play();}
    
     public static void Sound5()
{ new MP3Player(new File ("C:\\Program Files\\Airline Reservation System\\src\\system\\Users\\Audios\\user5.mp3")).play();}
    
     public static void Sound6()
{ new MP3Player(new File ("C:\\Program Files\\Airline Reservation System\\src\\system\\Users\\Audios\\otheruserslogin.mp3")).play();}
    
    private void jiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jiActionPerformed
        if(ji.isSelected())
        {
            Pass.setEchoChar((char)0);
        }
        else
        {
            Pass.setEchoChar('*');
        }
    }//GEN-LAST:event_jiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Loginpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel P;
    private javax.swing.JPasswordField Pass;
    private javax.swing.JLabel U;
    private javax.swing.JTextField User;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox ji;
    private javax.swing.JButton login;
    public static javax.swing.JTextField password;
    public static javax.swing.JTextField use;
    // End of variables declaration//GEN-END:variables

//method to call login of various users.
    
    private  void User()
       { 
           String pass= Pass.getText();
       
        String user= User.getText();
       
        {
            if (user.contains("Harsh")&&pass.contains("2.0")) {
            Pass.setText(null);
            User.setText(null);       
            setVisible(false);
            Form_fill1  Io=new Form_fill1();
            Io.setVisible(true);
            Sound6();}
            
         
        
  else if (user.contains("Vinod Sharma")&&pass.contains("Iron man of india")) {
            Pass.setText(null);
            User.setText(null);       
            setVisible(false);
            Form_fill1  Io=new Form_fill1();
            Io.setVisible(true);
            Sound2();}
            

 else if (user.contains("George")&&pass.contains("Intelligence")) {
            Pass.setText(null);
            User.setText(null);       
            setVisible(false);
            Form_fill1  Io=new Form_fill1();
            Io.setVisible(true);
            Sound1();}
         

      else   if (user.contains("Soniuhal")&&pass.contains("I love my bro")){
            Pass.setText(null);
            User.setText(null);       
            setVisible(false);
            Form_fill1  Io=new Form_fill1();
            Io.setVisible(true);
            Sound3();
      }
 
       else if (user.contains("Davinder")&&pass.contains("My lost friend")) {
            Pass.setText(null);
            User.setText(null);       
            setVisible(false);
            Form_fill1  Io=new Form_fill1();
            Io.setVisible(true);
            Sound5();
        } 
        else if (user.contains(use.getText())&&pass.contains(password.getText())) {
            Pass.setText(null);
            User.setText(null);       
            setVisible(false);
            Form_fill1  Io=new Form_fill1();
            Io.setVisible(true);
            Sound6();}
            
        else{
            JOptionPane.showMessageDialog(null,"INVALID LOGIN DETAILS","Login Error",JOptionPane.ERROR_MESSAGE);
        Pass.setText(null);
        User.setText(null);}}}}
