/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package system;

import jaco.mp3.player.MP3Player;
import java.io.File;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author jeeva
 */
public class Payment_method extends javax.swing.JFrame {

    public static int r;
    public Payment_method() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setExtendedState(JFrame.MAXIMIZED_HORIZ); 
        setResizable(false);
        Continue.setEnabled(false);
        a.setVisible(false);f.setVisible(false);
        b.setVisible(false);g.setVisible(false);
        c.setVisible(false);h.setVisible(false);
       d.setVisible(false);i.setVisible(false);
        e.setVisible(false);j.setVisible(false);k.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        b = new javax.swing.JLabel();
        d = new javax.swing.JLabel();
        f = new javax.swing.JLabel();
        i = new javax.swing.JLabel();
        j = new javax.swing.JLabel();
        a = new javax.swing.JLabel();
        g = new javax.swing.JLabel();
        e = new javax.swing.JLabel();
        c = new javax.swing.JLabel();
        h = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        rupee = new javax.swing.JLabel();
        dollar = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        Continue = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        k = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(837, 551));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Pay with Debit Card");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(30, 10, 380, 59);

        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton1);
        jRadioButton1.setBounds(10, 30, 20, 21);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Pay with Swiss/Bank Account\n");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(40, 200, 370, 44);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/Home/Payment-methods .1.jpg"))); // NOI18N
        jLabel5.setText("jd");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(300, 20, 330, 50);

        jRadioButton2.setText("jRadioButton2");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jRadioButton2);
        jRadioButton2.setBounds(10, 210, 20, 23);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Pay your booking amount using the debit card:\n "); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 74, 460, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("1.Mastercard 2.Visa 3.SBI 4.Paypal 4.Discover 5.ICCI 6.Punjab card 7.Axis\n");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 110, 710, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText(" All debit cards are acceptible here.");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 150, 660, 22);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Pay using your International  account in any one of the following:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(40, 270, 680, 22);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText(" 1.Swiss  2.Streamline 3.Barclays 4.Ulster bank 5.Paypal 6.2CC 7.Indian Bank Accounts");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(40, 290, 790, 22);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("If you Have account in another local banks then your payment is not acceptible.");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(40, 314, 730, 20);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/Home/Payment-methods .2.jpg"))); // NOI18N
        jLabel12.setText("jLabel12");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(410, 204, 310, 50);

        b.setText("jLabel15");
        jPanel1.add(b);
        b.setBounds(740, 40, 40, 14);

        d.setText("jLabel16");
        jPanel1.add(d);
        d.setBounds(740, 80, 40, 14);

        f.setText("jLabel17");
        jPanel1.add(f);
        f.setBounds(740, 120, 40, 14);

        i.setText("jLabel18");
        jPanel1.add(i);
        i.setBounds(740, 200, 40, 14);

        j.setText("jLabel19");
        jPanel1.add(j);
        j.setBounds(740, 220, 40, 14);

        a.setText("jLabel20");
        jPanel1.add(a);
        a.setBounds(740, 20, 40, 14);

        g.setText("jLabel21");
        jPanel1.add(g);
        g.setBounds(740, 150, 40, 14);

        e.setText("jLabel22");
        jPanel1.add(e);
        e.setBounds(740, 100, 40, 14);

        c.setText("jLabel23");
        jPanel1.add(c);
        c.setBounds(740, 60, 40, 14);

        h.setText("jLabel24");
        jPanel1.add(h);
        h.setBounds(740, 180, 40, 14);

        jPanel2.setBackground(new java.awt.Color(255, 255, 153));
        jPanel2.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("USD");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(510, 10, 110, 40);

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Or");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(350, 0, 60, 50);

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Rupees");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(220, 10, 90, 40);

        rupee.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        rupee.setText("jLabel15");
        jPanel2.add(rupee);
        rupee.setBounds(90, 10, 130, 40);

        dollar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        dollar.setText("jLabel16");
        jPanel2.add(dollar);
        dollar.setBounds(400, 10, 110, 40);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(20, 370, 740, 50);

        jPanel3.setBackground(new java.awt.Color(255, 255, 153));
        jPanel3.setLayout(null);

        jButton3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(102, 102, 255));
        jButton3.setText("Any help");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3);
        jButton3.setBounds(0, 0, 240, 50);

        Continue.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Continue.setText("Continue");
        Continue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinueActionPerformed(evt);
            }
        });
        jPanel3.add(Continue);
        Continue.setBounds(420, 0, 130, 50);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Cancel");
        jButton2.setMaximumSize(new java.awt.Dimension(115, 31));
        jButton2.setMinimumSize(new java.awt.Dimension(115, 31));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(610, 0, 120, 50);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(20, 460, 740, 50);

        k.setText("jTextField1");
        jPanel1.add(k);
        k.setBounds(739, 160, 50, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 840, 530);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       new MP3Player(new File("C:\\Program Files\\Airline Reservation System\\src\\system\\Home\\Cancel.mp3")).play(); 
        int x= JOptionPane.showConfirmDialog(null, "Do you want to exit and stop booking the tickets",
                "Cancel",JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE);
        if(x==JOptionPane.YES_OPTION)
        {
            this.dispose();
        }
        else
        {
            
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
   
        r=1;
         Continue.setEnabled(true);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         new MP3Player(new File ("C:\\Program Files\\Airline Reservation System\\src\\system\\Home\\hepler1.mp3")).play();
        String e="To enable Continue,please select Payment Method.(by using either debit card or by account)";
String rs="To choose any of them you need to click on buttons provided.For further details email us or contact us.";
String joiner=e+rs;
        JOptionPane.showMessageDialog(null,joiner);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void ContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinueActionPerformed
      
        if(r==1)
        {
            
          
        this.dispose();
        dr();
         new MP3Player(new File ("C:\\Program Files\\Airline Reservation System\\src\\system\\Home\\Debit card.mp3")).play();}
        else if(r==2)
        {
            ar();
            this.dispose();
            
             new MP3Player(new File ("C:\\Program Files\\Airline Reservation System\\src\\system\\Home\\final2.mp3")).play();
        }
    }//GEN-LAST:event_ContinueActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        r=2;
       Continue.setEnabled(true);
        
          
    }//GEN-LAST:event_jRadioButton2ActionPerformed

   private void dr()
   {
      Final_Form open=new Final_Form();
      Final_Form.da.setText(Payment_method.a.getText());
      Final_Form.db.setText(Payment_method.b.getText());
      Final_Form.dc.setText(Payment_method.c.getText());
      Final_Form.dd.setText(Payment_method.d.getText());
      Final_Form.de.setText(Payment_method.e.getText());
      Final_Form.df.setText(Payment_method.f.getText());
      Final_Form.dg.setText(Payment_method.g.getText());
      Final_Form.dh.setText(Payment_method.h.getText());
      Final_Form.di.setText(Payment_method.i.getText());
      Final_Form.dj.setText(Payment_method.j.getText());
      Final_Form.pricer.setText(Payment_method.rupee.getText());
      Final_Form.priced.setText(Payment_method.dollar.getText());
      Final_Form.rk.setText(Payment_method.k.getText());
        open.setVisible(true); 
   }
   private void ar()
   {
       Final_form2 open=new Final_form2();
            Final_form2.a1.setText(Payment_method.a.getText());
      Final_form2.b2.setText(Payment_method.b.getText());
      Final_form2.b3.setText(Payment_method.c.getText());
      Final_form2.b4.setText(Payment_method.d.getText());
      Final_form2.b5.setText(Payment_method.e.getText());
      Final_form2.b6.setText(Payment_method.f.getText());
      Final_form2.b7.setText(Payment_method.g.getText());
      Final_form2.b8.setText(Payment_method.h.getText());
      Final_form2.b9.setText(Payment_method.i.getText());
      Final_form2.b10.setText(Payment_method.j.getText());
   Final_form2.paisa.setText(Payment_method.rupee.getText());
   Final_form2.omg.setText(Payment_method.dollar.getText());
   Final_form2.bk.setText(Payment_method.k.getText());
      open.setVisible(true);
       
   }
            
        
   

                    
                         
          
    public static void main(String args[]) {
       
                new Payment_method().setVisible(true);
          
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Continue;
    public static javax.swing.JLabel a;
    public static javax.swing.JLabel b;
    public static javax.swing.JLabel c;
    public static javax.swing.JLabel d;
    public static javax.swing.JLabel dollar;
    public static javax.swing.JLabel e;
    public static javax.swing.JLabel f;
    public static javax.swing.JLabel g;
    public static javax.swing.JLabel h;
    public static javax.swing.JLabel i;
    public static javax.swing.JLabel j;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    public static javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    public static javax.swing.JTextField k;
    public static javax.swing.JLabel rupee;
    // End of variables declaration//GEN-END:variables
}
