/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package system;

import jaco.mp3.player.MP3Player;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author jeeva
 */
public class securityBleach extends javax.swing.JFrame {

    /**
     * Creates new form securityBleach
     */
    public securityBleach() {
        initComponents();
         setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setExtendedState(JFrame.MAXIMIZED_HORIZ); 
        setResizable(false);

        ji.setVisible(false);
        o.setVisible(false);
        l3.setVisible(false);
        l2.setVisible(false);
    }
 public class proghresso implements ActionListener{
       public void actionPerformed(ActionEvent evt){
         
           int n=ji.getValue();
       if(n<100)
         {
             n++;
             o.setText(Integer.toString(n)+"%");
             ji.setValue(n);
           
        
         }
         
         else{
           l2.setVisible(true);
           l3.setVisible(true);
           ji.setVisible(false);
           o.setVisible(false);
    timer.stop();
                   new MP3Player(new File("C:\\Program Files\\Airline Reservation System\\src\\system\\Admin\\Security pop.mp3")).play();
    String e="All the data would have been deleted if you have  not  clicked abort button.";
    String f="We have now successfully restored our deleted data.But Be very Careful next Time!! Now click yes to exit";
    String u=e+f;
    String h="We warn you to not enter PASSWORD If you are a costumer!!" ;
          JOptionPane.showConfirmDialog(null,u,h,JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
     if(JOptionPane.YES_NO_OPTION==1){
      setVisible(false);
     }else{
              setVisible(false);}
         
       }
     
           
       }}
 
      
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        ji = new javax.swing.JProgressBar();
        l3 = new javax.swing.JLabel();
        o = new javax.swing.JLabel();
        p = new javax.swing.JLabel();
        j = new javax.swing.JProgressBar();

        jFormattedTextField1.setText("jFormattedTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(640, 495));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/Admin/security bleach.jpg"))); // NOI18N
        jLabel1.setText("image of security bleach");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(140, 0, 230, 190);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("You have Entered Wrong Password.");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(40, 190, 400, 60);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Hurry! Click Abort unless Everything will be deleted. ");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(60, 260, 480, 40);

        l1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l1.setForeground(new java.awt.Color(255, 255, 255));
        l1.setText("Deleting process started.");
        jPanel1.add(l1);
        l1.setBounds(20, 380, 250, 40);

        l2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        l2.setForeground(new java.awt.Color(255, 255, 255));
        l2.setText(" Deleting process Stopped");
        jPanel1.add(l2);
        l2.setBounds(250, 370, 250, 50);

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Abort");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(410, 150, 100, 30);

        ji.setBackground(new java.awt.Color(255, 255, 255));
        ji.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ji.setForeground(new java.awt.Color(0, 0, 0));
        ji.setString("Sending Request  to stop  deleting everything...");
        ji.setStringPainted(true);
        jPanel1.add(ji);
        ji.setBounds(20, 320, 590, 20);

        l3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        l3.setForeground(new java.awt.Color(255, 255, 255));
        l3.setText("Request Accepted: Stop  DELETING... but 10% data deleted.");
        jPanel1.add(l3);
        l3.setBounds(40, 430, 570, 40);

        o.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        o.setForeground(new java.awt.Color(255, 255, 255));
        o.setText("10%");
        jPanel1.add(o);
        o.setBounds(280, 300, 70, 22);

        p.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        p.setForeground(new java.awt.Color(255, 255, 255));
        p.setText("10%");
        jPanel1.add(p);
        p.setBounds(410, 390, 50, 20);

        j.setBackground(new java.awt.Color(255, 255, 255));
        j.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(j);
        j.setBounds(260, 390, 146, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 640, 500);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ji.setVisible(true);
        o.setVisible(true);
        l1.setVisible(false);
        l2.setVisible(true);
        jLabel3.setVisible(false);
        timer = new Timer(200,new proghresso());
  
        timer.start(); 
        j.setVisible(false);
        p.setVisible(false);
  
       
    }//GEN-LAST:event_jButton1ActionPerformed

   
    public static void main(String args[]) {
        
                   securityBleach nj= new securityBleach();nj.setVisible(true);  
                    try{
                        for(int i=0;i<=10;i++){
                           Thread.sleep(150);
                           j.setValue(i);
                           p.setText(Integer.toString(i)+"");
                        }
                    }catch(Exception e){}
                  
    }
private  Timer timer;
private Timer timex;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JProgressBar j;
    private javax.swing.JButton jButton1;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar ji;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel o;
    public static javax.swing.JLabel p;
    // End of variables declaration//GEN-END:variables
}
