/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package system;
import jaco.mp3.player.MP3Player;
import javax.swing.Timer;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;


/**
 *
 * @author jeeva
 */
public class StartAdminSetup extends javax.swing.JFrame {

    /**
     * Creates new form StartAdminSetup
     */
    public StartAdminSetup() {
        initComponents();
        p.setVisible(false);
           close.setVisible(false);
    }
     private void m() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
   
    public static int u;
 public class proghresso implements ActionListener{
       public void actionPerformed(ActionEvent evt){
         int n=j.getValue();
       if(n<100)
         {
             n++;
             o.setText(Integer.toString(n)+"%");
             j.setValue(n);
        
        
         }
         
         else{
             timer.stop();
    Start.setVisible(false);
           o.setVisible(false);
           j.setVisible(false);
           p.setVisible(true);
           close.setVisible(true);
           
       }
         }
       }
 private  void o(){
     u=3;
 }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        j = new javax.swing.JProgressBar();
        o = new javax.swing.JLabel();
        Start = new javax.swing.JButton();
        close = new javax.swing.JButton();
        p = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(801, 29));
        setUndecorated(true);
        getContentPane().setLayout(null);

        j.setBackground(new java.awt.Color(255, 255, 255));
        j.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        j.setForeground(new java.awt.Color(102, 255, 102));
        j.setBorderPainted(false);
        j.setString("Loading the buttons. please wait..");
        j.setStringPainted(true);
        getContentPane().add(j);
        j.setBounds(0, 0, 670, 30);

        o.setBackground(new java.awt.Color(255, 255, 255));
        o.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        o.setText("100%");
        getContentPane().add(o);
        o.setBounds(670, 0, 60, 30);

        Start.setBackground(new java.awt.Color(255, 255, 255));
        Start.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        Start.setText("Start");
        Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartActionPerformed(evt);
            }
        });
        getContentPane().add(Start);
        Start.setBounds(730, 0, 70, 30);

        close.setBackground(new java.awt.Color(255, 255, 255));
        close.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        close.setText("Close it");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        getContentPane().add(close);
        close.setBounds(670, 0, 130, 30);

        p.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        p.setText("Everything loaded .. now please click close it");
        getContentPane().add(p);
        p.setBounds(0, 0, 670, 30);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 800, 30);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartActionPerformed
 new MP3Player(new File("C:\\Program Files\\Airline Reservation System\\src\\system\\Admin\\SP.mp3")).play();
        timer = new Timer(300,new proghresso());
  
        timer.start(); 
        
    }//GEN-LAST:event_StartActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_closeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
                new StartAdminSetup().setVisible(true);
              
              
         
    }
private Timer timer;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Start;
    private javax.swing.JButton close;
    private javax.swing.JProgressBar j;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel o;
    private javax.swing.JLabel p;
    // End of variables declaration//GEN-END:variables
}
