/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package system;

import jaco.mp3.player.MP3Player;
import java.io.File;

/**
 *
 * @author jeeva
 */
public class startSystem extends javax.swing.JFrame {

    /**
     * Creates new form startSystem
     */
    public startSystem() {
        initComponents();
        a1.setVisible(false);a2.setVisible(false);a3.setVisible(false);
        a4.setVisible(false);a5.setVisible(false);a6.setVisible(false);
        a7.setVisible(false);a8.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        j = new javax.swing.JProgressBar();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        o = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        a1 = new javax.swing.JLabel();
        a4 = new javax.swing.JLabel();
        a3 = new javax.swing.JLabel();
        a5 = new javax.swing.JLabel();
        a2 = new javax.swing.JLabel();
        a8 = new javax.swing.JLabel();
        a6 = new javax.swing.JLabel();
        a7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel15.setText("jLabel15");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(984, 466));
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/Home/Airplane_aeroplane_aircraft_jet_wallpapers__54_-removebg-preview.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 0, 680, 200);

        j.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        j.setForeground(new java.awt.Color(0, 255, 0));
        j.setString("Welcome Sir...Please wait till it loads.");
        j.setStringPainted(true);
        getContentPane().add(j);
        j.setBounds(70, 440, 870, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Made By-");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(790, 20, 200, 50);

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Harshdeep");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(780, 80, 200, 50);

        o.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        o.setText("100%");
        getContentPane().add(o);
        o.setBounds(400, 404, 100, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("Airline Ticket Reservation System");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(280, 220, 440, 40);

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("All");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(60, 4, 180, 50);

        jLabel17.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Copyrights");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(50, 60, 160, 30);

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText(" are reserved");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(50, 110, 240, 40);

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("2019");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(210, 50, 100, 50);

        jPanel1.setBackground(new java.awt.Color(0, 153, 255));
        jPanel1.setLayout(null);

        a1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        a1.setForeground(new java.awt.Color(255, 255, 255));
        a1.setText("Loading buttons....");
        jPanel1.add(a1);
        a1.setBounds(280, 310, 210, 30);

        a4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        a4.setForeground(new java.awt.Color(255, 255, 255));
        a4.setText("Gui enabled...");
        jPanel1.add(a4);
        a4.setBounds(630, 320, 180, 30);

        a3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        a3.setForeground(new java.awt.Color(255, 255, 255));
        a3.setText("Generating help buttons..\n");
        jPanel1.add(a3);
        a3.setBounds(290, 280, 280, 20);

        a5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        a5.setForeground(new java.awt.Color(255, 255, 255));
        a5.setText("Generating user list");
        jPanel1.add(a5);
        a5.setBounds(440, 330, 250, 40);

        a2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        a2.setForeground(new java.awt.Color(255, 255, 255));
        a2.setText("Generating forms...");
        jPanel1.add(a2);
        a2.setBounds(600, 280, 200, 30);

        a8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        a8.setForeground(new java.awt.Color(255, 255, 255));
        a8.setText("Ready to use");
        jPanel1.add(a8);
        a8.setBounds(380, 380, 240, 20);

        a6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        a6.setForeground(new java.awt.Color(51, 255, 51));
        a6.setText("We are sorry");
        jPanel1.add(a6);
        a6.setBounds(230, 400, 170, 30);

        a7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        a7.setForeground(new java.awt.Color(51, 255, 51));
        a7.setText(" for making you to wait");
        jPanel1.add(a7);
        a7.setBounds(480, 400, 290, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/Home/costume.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 170, 230, 260);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/system/Home/pilo.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(800, 120, 230, 390);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1030, 470);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws InterruptedException {
        startSystem s=new  startSystem();
        new MP3Player(new File("C:\\Program Files\\Airline Reservation System\\src\\system\\Home\\airplane-fly-by-01a.mp3")).play();
        try{
            for(int i=0;i<=20;i++)
            {
                s.setVisible(true);
                Thread.sleep(30);
                j.setValue(i);
                o.setText(Integer.toString(i)+"%");
                a1.setVisible(true);
                
                
            }
            
        } catch(Exception e){}
        
            try{
            for(int i=21;i<=30;i++)
            {
                s.setVisible(true);
                Thread.sleep(20);
                j.setValue(i);
                o.setText(Integer.toString(i)+"%");
                a2.setVisible(true);
                a1.setVisible(false);
            }
            
        } catch(Exception e){}
        
         try{
            for(int i=31;i<=50;i++)
            {
                s.setVisible(true);
                Thread.sleep(30);
                j.setValue(i);
                o.setText(Integer.toString(i)+"%");
                a3.setVisible(true);
                a2.setVisible(false);
            }
            
        } catch(Exception e){}
        
        try{
            for(int i=51;i<=65;i++)
            {
                s.setVisible(true);
                Thread.sleep(30);
                j.setValue(i);
                o.setText(Integer.toString(i)+"%");
                a4.setVisible(true);
                a3.setVisible(false);
            }
            
        } catch(Exception e){}
        try{
            for(int i=66;i<=80;i++)
            {
                s.setVisible(true);
                Thread.sleep(30);
                j.setValue(i);
                o.setText(Integer.toString(i)+"%");
                a5.setVisible(true);
                a4.setVisible(false);
                
            }
            
        } catch(Exception e){}
       
         try{
            for(int i=81;i<=100;i++)
            {
                s.setVisible(true);
                Thread.sleep(30);
                j.setValue(i);
                o.setText(Integer.toString(i)+"%");
                a6.setVisible(true);a7.setVisible(true);a8.setVisible(true);
                 a5.setVisible(false);
                
            }}
            catch(Exception e){}
            
             try{
           for(int i=101;i<=200;i++)
            {
            
                Thread.sleep(80);
                
            
               
                 
                
            }s.setVisible(false);
                new Home_page().setVisible(true);
            new MP3Player(new File("C:\\Program Files\\Airline Reservation System\\src\\system\\Home\\home.mp3")).play();
            
        } catch(Exception e){}
            
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel a1;
    public static javax.swing.JLabel a2;
    public static javax.swing.JLabel a3;
    public static javax.swing.JLabel a4;
    public static javax.swing.JLabel a5;
    public static javax.swing.JLabel a6;
    public static javax.swing.JLabel a7;
    public static javax.swing.JLabel a8;
    public static javax.swing.JProgressBar j;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel o;
    // End of variables declaration//GEN-END:variables
}
